import test from 'node:test';import assert from 'node:assert/strict';import '../data.js';import '../engine.js';
const E=HOH_ENGINE;
const options=overrides=>E.normalized({tiles:Array(80).fill(false).map((_,i)=>i<20),optional:[],premium:{premiumFarm:0,premiumHome:0,premiumCulture:0},fullArmy:false,interval:3,night:8,goodsTarget:0,sparkCap:0,goodsPerBatch:70,sparksPerBatch:95,workshopCounts:{jeweler:1,glassblower:1,alchemist:1},oldCount:0,compareSparks:false,...overrides});
test('production upper bound matches independent exhaustive area/workforce enumeration',()=>{const o=options(),cat=E.prepare(HOH_DATA.buildings,o),fixed=[...E.mandatory,...E.current].map(id=>cat[id]),output=(b,r)=>E.hourly(b,b.happyMax,r)*E.collectedHours(b.hours,o.interval,o.night),area=320-fixed.reduce((n,b)=>n+b.w*b.h,0),workers=fixed.reduce((n,b)=>n+b.workers-b.needs,0),constant=fixed.reduce((n,b)=>n+output(b,'food')+(b.kind==='workshop'?output(b,b.rewards[0].resource)*o.foodPerGood:0),0),goldBase=fixed.reduce((n,b)=>n+output(b,'coins'),0);let best=-Infinity;
for(let r=0;r*12<=area;r++)for(let d=0;r*12+d*16<=area;d++)for(let h=0;r*12+d*16+h*4<=area;h++)for(let m=0;r*12+d*16+h*4+m*9<=area;m++){
 if(workers+h+2*m<2*r+4*d)continue;const coins=goldBase+h*output(cat.smallHome,'coins')+m*output(cat.averageHome,'coins'),gold=Math.floor(Math.min(o.goldCap,coins)/o.goldPerBatch)*o.goldSparksPerBatch*o.foodPerSpark;
 best=Math.max(best,constant+r*output(cat.ruralFarm,'food')+d*output(cat.domesticFarm,'food')+gold);
}const b=E.productionBound(cat,o);assert.equal(b.feasible,true);assert.ok(b.total>=best);assert.ok(b.total-best<=1.01);});
test('upper bound cannot become smaller by unlocking land and rejects impossible fixed area',()=>{const o=options(),cat=E.prepare(HOH_DATA.buildings,o),a=E.productionBound(cat,o),b=E.productionBound(cat,{...o,tiles:Array(80).fill(true)});assert.ok(b.total>=a.total);assert.equal(E.productionBound(cat,{...o,tiles:Array(80).fill(false)}).feasible,false);});
test('lossy furnace conversion includes the upper value just below an exchange threshold',()=>{const o=options({oldCount:1,sparkCap:100000,goodsPerBatch:100000,sparksPerBatch:1,foodPerSpark:0,goldSparksPerBatch:0}),cat=E.prepare(HOH_DATA.buildings,o),unconverted=E.productionBound(cat,o),lossy=E.productionBound(cat,{...o,goodsPerBatch:100});assert.ok(lossy.total<=unconverted.total);assert.ok(lossy.total>0);const b=cat.stoneMason,max=E.hourly(b,b.happyMax,b.rewards[0].resource)*E.collectedHours(b.hours,o.interval,o.night);assert.ok(Math.abs((unconverted.total-lossy.total)-(max-100)*o.foodPerGood)<1.01);});
test('ten-minute budget is accepted without accepting arbitrary or invalid durations',()=>{E.validateOptions(options({searchSeconds:600}));E.validateOptions(options({searchSeconds:300}));assert.throws(()=>E.validateOptions(options({searchSeconds:599})));});
