import test from 'node:test';import assert from 'node:assert/strict';import '../data.js';import '../engine.js';
const E=HOH_ENGINE,data=HOH_DATA.buildings;
const common=E.normalized({tiles:Array(80).fill(true).map((_,i)=>!(i<40&&i%10<3||i>=40&&i<50&&i%10<2)),interval:3,night:8,goodsTarget:2800,sparkCap:7000,goodsPerBatch:70,sparksPerBatch:95,premium:{premiumFarm:0,premiumHome:0,premiumCulture:1},optional:['collectableMinoanWatchtowerV2'],towerLevel:3,fountain:true,fountainLevel:32,fountainPoints:5000,fountainRange:3,balanced:false,goalVersion:4,engineMode:'frontiers',fullArmy:true,oldCount:0,compareSparks:false,searchStarts:3,workshopCounts:{jeweler:2,glassblower:2,alchemist:2}});
function solve(o){const cat=E.prepare(data,o);for(let seed=1;seed<=3;seed++){const c=E.searchFrontiers(cat,o,o.oldCount,seed);if(c){assert.equal(E.validate(c.list,c.options,cat),null);return c;}}assert.fail('No valid frontier layout');}
test('opposing fronts produce a useful compact city with all barracks happy',()=>{const c=solve({...common,interval:1,night:1});/* hourly collection: rural farms, the compact 4x3 rows this check was written for */assert.equal(c.stats.army,1);assert.ok(c.stats.food>5_800_000);assert.ok(1056-c.stats.used<=64,'unused cells: '+(1056-c.stats.used));/* hole retiling inside the constructor is time-boxed, so under a loaded test run a few more cells stay free */assert.ok(c.groupRepairs>0);assert.ok(c.stats.spare>=0);for(const id of E.current)assert.equal(c.list.filter(b=>b.id===id).length,2);});
test('furnace variant covers actual collections rather than nominal 24 hours',()=>{const o={...common,oldCount:6,requireFuel:true},c=solve(o);assert.ok(c.stats.oldGoods>=7000);assert.equal(c.list.filter(b=>b.oldWorkshop).length,6);const restored=E.readProject(data,E.projectFile(o,c));assert.equal(restored.options.engineMode,'frontiers');assert.equal(restored.result.choices[0].stats.food,c.stats.food);});
test('second engine preserves premium and optional buildings on a different terrain',()=>{const o={...common,tiles:Array(80).fill(true),premium:{premiumFarm:2,premiumHome:3,premiumCulture:2},optional:['collectableSchoolV2','collectableArchitectsStudioV2','heroAcademy','collectableMinoanWatchtowerV2'],towerLevel:10};const c=solve(o);for(const id of [...E.mandatory,...o.optional])assert.equal(c.list.filter(b=>b.id===id).length,1);for(const [id,n]of Object.entries(o.premium))assert.equal(c.list.filter(b=>b.id===id).length,n);});
test('fronts adapt to mirrored land and an internal cutout',()=>{for(const tiles of [common.tiles.map((_,i)=>common.tiles[Math.floor(i/10)*10+9-i%10]),Array(80).fill(true).map((_,i)=>![0,1,2,3,4,5,6,7,8,9,34,35,44].includes(i))])solve({...common,tiles});});
test('engine comparison reports equal target budgets, measured outcomes and validates every returned city',async()=>{const o={...common,engineMode:'compare'},r=await E.generate(data,o);assert.equal(r.benchmarks.length,2);assert.deepEqual(r.benchmarks.map(b=>b.budgetMs),[3000,3000]);for(const b of r.benchmarks){assert.ok(b.elapsedMs>=0);assert.ok(b.runs>=1||b.found,'a later engine may start from the city of the earlier engine instead of constructing');if(!b.found)assert.equal(b.total,null);}for(const c of r.choices)assert.equal(E.validate(c.list,c.options,r.cat),null);assert.ok(r.choices.some(c=>c.engine==='frontiers'));});
